### ISSUE TITLE
Getting app ready for live testing

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#228]
### **Things that need doing prior to live testing**

- [x] Upgrade Heroku (requires card details) - this is so the app doesn't take 30 seconds to spin up 
- [x] Set up Google Analytics
- [x] Remove links to view Feedback

### **Dependent on whether client / therapist is fine with this not being on the app before the platform or not**

- [ ] Terms of Use -> we need the link to be provided #12 
- [ ] Privacy Policy -> we need the link to be provided #12 
- [ ] The wording to put on your Cookies message -> You don't need a whole policy but you need to have an intro paragraph to replace the existing one that's on there (open the app in incognito mode to see it again) #12 

**IMPORTANT**
Are they fine with their data / content being potentially deleted at the end? This might not happen, but just wanted to check whether this is not production data, or testing data we can then delete if needed as part of a rebuild. 

### Questions

- [x] Should we shift to the proper email address?
- [ ] Do you want it added to a proper url or are you fine using this heroku one for now?
- [x] Are you fine with the client experiencing bugs if you haven't had a chance to re-test the ones we have fixed?

**Comment by IreneCMT** [comment]
Terms of Use and Privacy Policy Here: [https://drive.google.com/file/d/10HNCtdLfqY8RkVvD8h0Ufxs5yR32R098/view?usp=sharing](url)

**Comment by IreneCMT** [comment]
Upgrading Heroku means starting the monthly payments I suppose?

**Comment by IreneCMT** [comment]
In regards to the IMPORTANT section question, yes, that's ok. We know this is a test so if needed to be deleted that's ok.

**Comment by thejoefriel** [comment]
**Actions from our meeting**
- Regarding cookie -> Joe to look at and advise on a paragraph to put in 
- Shift over to the actual email

**Comment by thejoefriel** [comment]
Hey @IreneCMT I noticed that the privacy policy in the T&C's seems to be client specific. Is there a different Therapist one you need us to include?
