### ISSUE TITLE
I can send a progress update (BACK)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#62]
**Note:**
This includes both sides of this feature. So it includes:
- Client sending an update
- Therapist viewing an update and replying

__Related issue(s)__

#61 

__Wireframe link__

N/A

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [ ] Connect with front end #61 
- [ ] Use upload feature to store file in S3 #31 
- [ ] Api call and db query to store reference to the update for this programme
- [ ] Api call and db query to store reference to the update therapist reply for this programme
- [ ] Fetch the update for the therapist (if media content then use the streaming feature #35 )
     - [ ] Check if therapist has sent response already
- [ ] Trigger email #49 to notify therapist
- [ ] Trigger email #49 to notify client when therapist sends reply
