### ISSUE TITLE
I can add a new programme (BACK)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#64]
__Related issue(s)__

#63 

__Wireframe link__

N/A

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Connect with front end, including S3 upload feature #31 
- [x] Api call & db query set up to create programme and store content (also uploaded file, if present)
- [x] Trigger email to send to client (should already be created in #49)
- [ ] If not already created, I believe we need a cron job to check at the end of each day and delete files that were uploaded but not linked to any programme or library
- [x] For Review & Finish page, api call to fetch relevant files from S3 for final review (connect with #35 and #31 features)

**Comment by dupreesi** [comment]
When starting on the add content part please check pages/Therapist/CreateProgram and build on this
