### ISSUE TITLE
I can edit a programme (FRONT)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#65]
__Related issue(s)__

Make sure #63 is done first as this is basically the Review & Finish page

__Wireframe link__
https://www.figma.com/file/CcYmhfnXreAPxlfyEmGsAH/Chiltern-Music-Therapy?node-id=805%3A12633

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Should use the front end created for the Review & Finish page in the add programme issue #63 
- [x] Design pages in line with wireframes
- [x] Show success message when updated
- [x] Validation to ensure all required fields filled in (refer to #63 for full details on validation)
- [x] Show remove modal prompt if selected
- [x] If user selects add more content take them through the add content flow that has been set up in #63 but with a boolean flag so we can see this is part of an existing programme with it's own state

**Comment by dupreesi** [comment]
please make sure to re-use components that are used in create a programme flow (e.g. for adding new content / editing existing content)
