### ISSUE TITLE
I can edit a programme (BACK)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#66]
__Related issue(s)__

#65
Also make sure #64 has been completed as a lot of the work here will help regarding file uploads etc

__Wireframe link__

N/A

---

### Acceptance Criteria:

_REMEMBER THAT WHOEVER WORKS ON THIS ISSUE MUST TICK OFF ALL THE POINTS IN THIS LIST UNLESS THERE IS CLEAR AGREEMENT IN THE COMMENTS TO SAY OTHERWISE. **DO NOT REVIEW A PR INVOLVING THIS ISSUE UNLESS THIS HAS BEEN DONE**_ 

- [x] Connect to front end of #65 
- [x] Set up api calls and db queries to update references in database to content and programme
- [ ] If any content removed that has files in S3, check if that content is part of library. If not then delete file from S3
- [x] Trigger email update to client (should be covered in #49)
- [x] If user selects add more content take them through the add content flow that has been set up in #64
