### ISSUE TITLE
User Testing - UX testing

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/chiltern-music-therapy#9]
### Summary 
We want to use an interactive design prototype to carry out testing with our potential users. This lets us test and validate the user journeys and stories we have built, making sure the tool can be used in the way we intend it to be used, and then making any changes.

By doing this we can really define on the most essential features and make changes at the design stage which is always quicker to do than in development stage. 

**What we need**
- Ideally 3-5 users **per** user type/persona
- Each session is 30-45 minutes
- You need ideally 2 people from CMT/Yalla to handle the session
- Sessions are carried out remotely and the only thing the user needs is:
    - A computer with connection to internet
    - Any browser (that isn't Internet Explorer ideally!) 

**FULL DETAILS ABOUT USER TESTING, ALONG WITH EXAMPLES OF SCRIPTS, PROTOTYPES ETC, CAN BE FOUNDER HERE**
https://www.notion.so/User-Testing-852be476a6304069ae445f005084f3cd

### Suggested dates for user testing
16th - 18th March

### Tasks:
**Booking in user tests**
- [ ] Agree who is reaching out to the users
    - If CMT to reach out then Yalla will write a template email to help
    - If Yalla to reach out then CMT to send over contact details
- [ ] Agree consent process - do you have a form you would like us to use @IreneCMT or should we send across ours for you to review?
- [ ] Add each test to the schedule (link below)
- [ ] Add who is assigned to work each testing session

**Preparing for user tests**
- [ ] Add link to the Figma prototype
- [ ] Add link to User Testing script(s)
- [ ] Add link to User Testing Feedback Form

**Storing testing results**
- [ ] Store the first round UX / low res user testing sessions in the link below

### Overview of testing schedules, scripts and feedback pages: 
https://www.notion.so/UX-User-Testing-c6d83fbc0a0445feb120e1aaea9e12ae

### Prototype links
TBC

**Comment by thejoefriel** [comment]
Duplicate
